# Generated by Django 3.2.11 on 2022-03-18 10:40
from datetime import datetime

from django.db import migrations
from django.db.models import Q

from MyBank.settings import LOAD_TEST_DATA


def create_superuser(apps, schema_editor):
    UserModel = apps.get_model("auth", "User")
    UserModel.objects.create_superuser(username='admin',
                                       email='admin@mybank.com',
                                       password='admin')


def load_fixture(apps, schema_editor):
    if LOAD_TEST_DATA:
        UserModel = apps.get_model("auth", "User")
        user = UserModel.objects.get(username='admin')

        person_list = []
        PersonModel = apps.get_model("Account", "Person")

        person_list.append(PersonModel(first_name='Claire',
                                       last_name='Bennet',
                                       iban='ES4401283361616974956685',
                                       created_timestamp=datetime.now(),
                                       updated_timestamp=datetime.now(),
                                       created_by=user,
                                       updated_by=user))
        person_list.append(PersonModel(first_name='Peter',
                                       last_name='Petrelli',
                                       iban='ES2820803268183812692758',
                                       created_timestamp=datetime.now(),
                                       updated_timestamp=datetime.now(),
                                       created_by=user,
                                       updated_by=user))
        person_list.append(PersonModel(first_name='Niki',
                                       last_name='Sanders',
                                       iban='ES6601826735167875424365',
                                       created_timestamp=datetime.now(),
                                       updated_timestamp=datetime.now(),
                                       created_by=user,
                                       updated_by=user))
        person_list.append(PersonModel(first_name='Matt',
                                       last_name='Parkman',
                                       iban='ES8500819131171475526498',
                                       created_timestamp=datetime.now(),
                                       updated_timestamp=datetime.now(),
                                       created_by=user,
                                       updated_by=user))

        PersonModel.objects.bulk_create(person_list)


def unload_fixture(apps, schema_editor):
    PersonModel = apps.get_model("Account", "Person")
    PersonModel.objects.filter(Q(iban='ES4401283361616974956685') |
                               Q(iban='ES2820803268183812692758') |
                               Q(iban='ES6601826735167875424365') |
                               Q(iban='ES8500819131171475526498')).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
